name = "avo"
description = ""
keywords = "music"
image = "jake.webp"
theme = "dark"
primary_color = "#d81b60"
text_align = "center"
gtag_id = "G-33WB8LVHR6"
base_url = "https://soundcloud.com/aavoo"

[[sections]]
title = "Socials"
description = ""
direction = "column"
item_style = "outline"
[[sections.items]]
title = "Spotify"
description = ""
url = "https://open.spotify.com/artist/6f6Ib4dPpABT7RYDSSyXS0"
[[sections.items]]
title = "YouTube"
description = ""
url = "https://www.youtube.com/@avolition"
[[sections.items]]
title = "TikTok"
description = ""
url = "https://www.tiktok.com/@atomicnumber18"

[[sections]]
title = ""
description = ""
direction = "row"
item_style = "filled"
[[sections.items]]
title = ""
url = ""
[[sections.items]]
title = ""
url = ""
[[sections.items]]
title = ""
url = ""
[[sections.items]]
title = ""
url = ""
